config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { registrations: 'registrations' }
  root to: 'pages#index'
  resources :articals
  get 'pages/contact'
  get 'pages/about'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artical.rb
class Artical < ApplicationRecord
  belongs_to :user, :optional => true
  has_many :comments
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :artical
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :articals
  has_many :comments

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articals_controller.rb
class ArticalsController < ApplicationController
  before_action :set_artical, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /articals or /articals.json
  def index
    @articals = Artical.all
  end

  # GET /articals/1 or /articals/1.json
  def show
  end

  # GET /articals/new
  def new
    @artical = current_user.articals.build
  end

  # GET /articals/1/edit
  def edit
  end

  # POST /articals or /articals.json
  def create
    @artical = current_user.articals.build(artical_params)

    respond_to do |format|
      if @artical.save
        format.html { redirect_to @artical, notice: "Artical was successfully created." }
        format.json { render :show, status: :created, location: @artical }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @artical.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articals/1 or /articals/1.json
  def update
    respond_to do |format|
      if @artical.update(artical_params)
        format.html { redirect_to @artical, notice: "Artical was successfully updated." }
        format.json { render :show, status: :ok, location: @artical }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @artical.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articals/1 or /articals/1.json
  def destroy
    @artical.destroy
    respond_to do |format|
      format.html { redirect_to articals_url, notice: "Artical was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_artical
      @artical = Artical.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def artical_params
      params.require(:artical).permit(:title, :body)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @articals =Artical.all
  end

  def contact
  end

  def about
  end
end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController
  private
  def sign_up_params
    params.require(:user).permit(
      :email,
      :password,
      :password_confirmation,
      :username,
      :firstname,
      :lastname
    )
  end
  def account_update_params
    params.require(:user).permit(
      :email,
      :password,
      :password_confirmation,
      :current_password,
      :username,
      :firstname,
      :lastname
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articals_helper.rb
module ArticalsHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articals/_form.html.erb
<%= form_with(model: artical) do |form| %>
  <% if artical.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(artical.errors.count, "error") %> prohibited this artical from being saved:</h2>

      <ul>
        <% artical.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/articals/edit.html.erb
<h1>Editing Artical</h1>

<%= render 'form', artical: @artical %>

<%= link_to 'Show', @artical %> |
<%= link_to 'Back', articals_path %>

app/views/articals/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Articals</h1>

<table class="table table-striped">
  <thead>
    <tr>
      <th>Created by</th>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articals.each do |artical| %>
      <tr>
        <td><%= artical.user.username %></td>
        <td><%= artical.title %></td>
        <td><%= artical.body %></td>
        <td><%= link_to 'Show', artical %></td>
        <td><%= link_to 'Edit', edit_artical_path(artical) %></td>
        <td><%= link_to 'Destroy', artical, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Artical', new_artical_path %>

app/views/articals/new.html.erb
<h1>New Artical</h1>

<%= render 'form', artical: @artical %>

<%= link_to 'Back', articals_path %>

app/views/articals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Created by:</strong>
  <%= @artical.user.username %>
</p>
<p>
  <strong>Title:</strong>
  <%= @artical.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @artical.body %>
</p>

<%= link_to 'Edit', edit_artical_path(@artical) %> |
<%= link_to 'Back', articals_path %>

app/views/layouts/_foot.html.erb
<footer class="footer-distributed navbar-fixed-bottom">
  <div class="footer-right">
    <a href="#"><i class="fa fa-facebook"></i></a>
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-linkedin"></i></a>
    <a href="#"><i class="fa fa-github"></i></a>
  </div>
  <div class="footer-left">
    <p class="footer-links">
      ·
      <%= link_to "Contact Us", pages_contact_path, class: "page-scroll" %>
      ·
      <%= link_to "About Us", pages_about_path, class: "page-scroll" %>
      ·
    </p>
    <p> </p>
  </div>
</footer>

app/views/layouts/_nav.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-
example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
     <%= link_to "Nauman Articals", root_path, class: 'navbar-brand' %>
    </div>
    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">

        <li><a href="#">Link</a></li>

      </ul>
      <ul class="nav navbar-nav navbar-right">

        <li><%= link_to "Contact Us", pages_contact_path %></li>
        <li><%= link_to "About us", pages_about_path %></li>
        <li><%= link_to "Create an Article", new_artical_path %></li>
        <% if !current_user %>
        <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <li><%= link_to "Sign in", new_user_session_path %></li>

<% else %>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
             aria-expanded="false"><%= current_user.username %> <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li><%= link_to "Edit My Profile", edit_user_registration_path %></li>
            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
          </ul>
        </li>
      </ul>
          <% end %>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Nauman's Articals</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </head>

  <body>
  <%= render 'layouts/nav' %>
  <%= bootstrap_flash %>
  <div class="container">
    <%= yield %>
  </div>
  <%= render 'layouts/foot' %>
  </body>
</html>

app/views/pages/about.html.erb
<div class="row">
  <div class="col-lg-12 text-center">
    <h1>About Us</h1>
    <p class="lead">
      The Amazons of DC Comics are a race of warrior women who exist as part of Greek mythology. They live on Paradise Island, later known as Themyscira, an isolated location in the middle of the ocean where they are hidden from Man's World (rest of the world).

      Depending on the origin story, they are the creation of Aphrodite or were created from clay by a coterie of Olympian gods over three thousand years ago to serve as their messengers to the world in the name of peace and justice. For centuries, the women thrived in safety and security apart from a hostile, male-dominated world. As long as Amazons remain on Themyscira they do not age. Circumstances involving the unexpected arrival of Steve Trevor forced their existence to be revealed to the modern world.[1][2]

      There have been numerous incarnations of these Amazons after Marston's original depictions: Robert Kanigher's revised depiction (highlighted by the change of Queen Hippolyta's hair from brunette to blonde), George Pérez's reworking following the Crisis, and changes subsequent to Infinite Crisis and The New 52. What these groups have in common is that they are the people from which came DC Comics' superheroine Wonder Woman.
    </p>

    </ul>
  </div>
</div>

app/views/pages/contact.html.erb
<div class="row">
  <div class="col-lg-12 text-center">
    <h1>Contact Us</h1>
    <p class="lead">
      The Next.js framework utilizes JAMstack architecture, which distinguishes between front-end and back-end and allows for efficient front-end development that is independent of any back-end APIs.[1] The framework supports common CSS as well as precompiled Scss and Sass, CSS-in-JS, and styled JSX.[11] In addition, it is built with TypeScript support and smart bundling.[20] The open source transpiler Babel is used to transform and compile code into JavaScript usable by a browser. Webpack, another open-source tool, is used to bundle the modules afterwards. All of these tools are used with npm in a terminal.[12]

      The main feature of Next.js is its use of server-side rendering to reduce the burden on web browsers and provide enhanced security[citation needed]. This can be done for any part of the application or the entire project, allowing for content-rich pages to be singled out for server-side rendering.[8] It can also be done only for first time visitors, to reduce the burden on web browsers that have yet to download any of the site's assets.[9] The "hot reloading" feature detects changes as they are made and re-renders the appropriate pages so the server avoids the need to be restarted. This allows changes made to the application code to be immediately reflected in the web browser, though some browsers will require the page to be refreshed.[8] The software uses page-based routing for developer convenience and includes support for dynamic routing. Other features include hot-module replacement so that modules can be replaced live, automatic code splitting, which only includes code necessary to load the page, and page prefetching to reduce load time.[8]
    </p>

  </div>
</div>

app/views/pages/index.html.erb
<div class="row">
  <!-- Blog Post Content Column -->
  <div class="col-lg-8">
    <!-- Blog Post -->
    <!-- Title -->
    <h1>Blog Post Title</h1>
    <!-- Author -->
    <p class="lead">
      by <a href="#">Start Bootstrap</a>
    </p>
    <hr>
    <!-- Date/Time -->
    <p><span class="glyphicon glyphicon-time"></span> Posted on August 24, 2013 at 9:00 PM</p>
    <hr>
    <!-- Preview Image -->
    <img class="img-responsive" src="http://placehold.it/900x300" alt="">
    <hr>
    <!-- Post Content -->
    <p class="lead">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ducimus, vero,
      obcaecati, aut, error quam sapiente nemo saepe quibusdam sit excepturi nam quia corporis eligendi
      eos magni recusandae laborum minus inventore?</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Ut, tenetur natus doloremque laborum
      quos iste ipsum rerum obcaecati impedit odit illo dolorum ab tempora nihil dicta earum fugiat.
      Temporibus, voluptatibus.</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Eos, doloribus, dolorem iusto
      blanditiis unde eius illum consequuntur neque dicta incidunt ullam ea hic porro optio ratione repellat
      perspiciatis. Enim, iure!</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Error, nostrum, aliquid, animi, ut quas
      placeat totam sunt tempora commodi nihil ullam alias modi dicta saepe minima ab quo voluptatem
      obcaecati?</p>
    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Harum, dolor quis. Sunt, ut, explicabo,
      aliquam tenetur ratione tempore quidem voluptates cupiditate voluptas illo saepe quaerat numquam
      recusandae? Qui, necessitatibus, est!</p>
    <hr>
    <!-- Blog Comments -->
    <!-- Comments Form -->
    <div class="well">
      <h4>Leave a Comment:</h4>
      <form role="form">
        <div class="form-group">
          <textarea class="form-control" rows="3"></textarea>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
      </form>
    </div>
    <hr>
    <!-- Posted Comments -->
    <!-- Comment -->
    <div class="media">
      <a class="pull-left" href="#">
        <img class="media-object" src="http://placehold.it/64x64" alt="">
      </a>
      <div class="media-body">
        <h4 class="media-heading">Start Bootstrap
          <small>August 25, 2014 at 9:30 PM</small>
        </h4>
        Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin
        commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc
        ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
      </div>
    </div>
    <!-- Comment -->
    <div class="media">
      <a class="pull-left" href="#">
        <img class="media-object" src="http://placehold.it/64x64" alt="">
      </a>
      <div class="media-body">
        <h4 class="media-heading">Start Bootstrap
          <small>August 25, 2014 at 9:30 PM</small>
        </h4>
        Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin
        commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc
        ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
        <!-- Nested Comment -->
        <div class="media">
          <a class="pull-left" href="#">
            <img class="media-object" src="http://placehold.it/64x64" alt="">
          </a>
          <div class="media-body">
            <h4 class="media-heading">Nested Start Bootstrap
              <small>August 25, 2014 at 9:30 PM</small>
            </h4>
            Cras sit amet nibh libero, in gravida nulla. Nulla vel metus scelerisque ante sollicitudin
            commodo. Cras purus odio, vestibulum in vulputate at, tempus viverra turpis. Fusce condimentum nunc
            ac nisi vulputate fringilla. Donec lacinia congue felis in faucibus.
          </div>
        </div>
        <!-- End Nested Comment -->
      </div>
    </div>
  </div>
  <!-- Blog Sidebar Widgets Column -->
  <div class="col-md-4">
    <!-- Blog Search Well -->
    <div class="well">
      <h4>Blog Search</h4>
      <div class="input-group">
        <input type="text" class="form-control">
        <span class="input-group-btn">
<button class="btn btn-default" type="button">
<span class="glyphicon glyphicon-search"></span>
</button>
</span>
      </div>
      <!-- /.input-group -->
    </div>
    <!-- Blog Categories Well -->
    <div class="well">
      <h4>Blog Categories</h4>
      <div class="row">
        <div class="col-lg-6">
          <ul class="list-unstyled">
            <li><a href="#">Category Name</a>
            </li>
            <li><a href="#">Category Name</a>
            </li>
            <li><a href="#">Category Name</a>
            </li>
            <li><a href="#">Category Name</a>
            </li>
          </ul>
        </div>
        <div class="col-lg-6">
          <ul class="list-unstyled">
            <li><a href="#">Category Name</a>
            </li>
            <li><a href="#">Category Name</a>
            </li>
            <li><a href="#">Category Name</a>
            </li>
            <li><a href="#">Category Name</a>
            </li>
          </ul>
        </div>
      </div>
      <!-- /.row -->
    </div>
    <!-- Side Widget Well -->
    <div class="well">
      <h4>Recents Posts</h4>
      <% @articals.each do |a| %>
        Created by: <%= a.user.username %><br />
        <strong><%= link_to a.title, a %></strong>
        <p><%= truncate(a.body) %></p>
      <% end %>
    </div>
  </div>
</div>
<!-- /.row -->
<hr>